FROM ghcr.io/detjensrobert/toolbx-images:arch

# install editor packages, etc over base image

# add rubygems repo for solargraph gem
RUN echo -e '[quarry]\nServer = https://pkgbuild.com/~anatolik/quarry/x86_64/' >> /etc/pacman.conf

COPY ./packages /
RUN pacman -Syu --needed --noconfirm $(cat /packages | grep -v '#' | xargs)  && \
    pacman -Scc --noconfirm --clean && rm /packages

COPY ./aur-packages /
RUN useradd yaybuilder --groups wheel --create-home && \
    sudo -u yaybuilder yay -Sy --noconfirm $(cat /aur-packages | grep -v '#' | xargs) && \
    userdel yaybuilder && \
    rm -rf /home/yaybuilder && \
    pacman -Scc --noconfirm --clean && rm /aur-packages
