FROM quay.io/toolbx/ubuntu-toolbox:24.04

COPY ./packages /
RUN apt-get update && \
    apt-get install -y $(cat /packages | grep -v '#' | xargs) && \
    rm -rd /var/lib/apt/lists/* && rm /packages

# fix bat program name
RUN ln -s /usr/bin/batcat /usr/bin/bat

# pre set distrobox host links
RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/firefox && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/systemctl && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/journalctl && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/flatpak
