FROM quay.io/toolbx/ubuntu-toolbox:24.04

RUN echo "en_US.UTF-8" > /etc/locale.gen

RUN apt-get update

RUN apt-get install -y apt-file && \
    apt-file update

COPY ./packages /
RUN apt-get install -y $(cat /packages | grep -v '#' | xargs) && rm /packages

# fix bat program name
RUN ln -s /usr/bin/batcat /usr/bin/bat

# pre set distrobox host links
RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/firefox && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/systemctl && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/journalctl && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/flatpak
