FROM quay.io/toolbx/arch-toolbox:latest

# set pacman mirrors
# RUN pacman -Sy --noconfirm reflector && \
#     reflector --country us --protocol https --latest 10 --sort rate --save /etc/pacman.d/mirrorlist
COPY <<'EOF' /etc/pacman.d/mirrorlist
Server = https://ziply.mm.fcix.net/archlinux/$repo/os/$arch
Server = https://mirror.fcix.net/archlinux/$repo/os/$arch
EOF
RUN cat /etc/pacman.d/mirrorlist

# yes putting pacman key in a container image is "bad"
# but this is a very low volume image and i dont care
RUN pacman-key --init && \
    pacman -Sy --noconfirm archlinux-keyring && \
    pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com && \
    pacman-key --lsign-key 3056513887B78AEB && \
    pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' && \
    pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' && \
    echo -ne "\n\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist\n" | tee -a /etc/pacman.conf

# twiddle some pacman settings
RUN sed -i -E /etc/pacman.conf \
    -e 's/^#Color/Color/' \
    -e 's/^NoProgressBar/#NoProgressBar/' \
    -e '\|^NoExtract.+usr/share/man|d' && \
    sed -i -E /etc/makepkg.conf \
    -e 's/^#MAKEFLAGS=.+/MAKEFLAGS="-j$(nproc)"/' \
    -e '/OPTIONS/s/ debug/ !debug/'

# reinstall packages with manpages
RUN pacman -Fy --noconfirm && pacman -Sy --noconfirm && \
    pacman -Qq $(pacman -Fq /usr/share/man/ | cut -d/ -f2) 2> /dev/null | pacman -S --noconfirm - && \
    pacman -Scc --noconfirm --clean

# and install other extra packages
COPY ./packages /
RUN pacman -Syu --needed --noconfirm $(cat /packages | grep -v '#' | xargs) && \
    pacman -Scc --noconfirm --clean && rm /packages

# run yay as temp user
# yay tries to read /dev/tty as stdin, there is no tty here! ugh
COPY ./aur-packages /
RUN useradd yaybuilder --groups wheel --create-home && \
    sudo -u yaybuilder yay -Sy --noconfirm --cleanafter --mflags="--nocheck" $(cat /aur-packages | grep -v '#' | xargs) && \
    userdel yaybuilder && \
    rm -rf /home/yaybuilder && \
    pacman -Scc --noconfirm --clean && rm /aur-packages

COPY <<EOF /etc/ssh/sshd_config.d/localhost-only.conf
Port 2222
ListenAddress 127.0.0.1

PasswordAuthentication no
AuthenticationMethods publickey

# allow socket forwarding to remove existing sockets
# https://wiki.gnupg.org/AgentForwarding
StreamLocalBindUnlink yes
EOF

# fix podman-docker to use PATH
RUN sed -i -E 's|exec .+podman|exec podman|' $(find /usr -name docker)

# pre set distrobox host links
RUN for f in systemctl journalctl xdg-open firefox flatpak op podman; do \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/$f; \
    done

# make podman command remote
# use RUN echo since copy heredoc is interpreting the $@ and escaping doesnt help
#COPY --chmod=755 <<EOF /usr/local/bin/podman-remote
##!/bin/sh
#exec /usr/bin/podman --remote "$@"
#EOF
RUN echo -e '#!/bin/sh\nexec /usr/bin/podman --remote "$@"' > /usr/local/bin/podman-remote && \
    chmod +x /usr/local/bin/podman-remote

LABEL io.containers.autoupdate=registry \
    name="Custom Archlinux Toolbox" \
    maintainer=detjensrobert \
    org.opencontainers.image.source="https://github.com/detjensrobert/toolbx-images"
