FROM quay.io/fedora/fedora-toolbox:latest
# FROM quay.io/fedora/fedora-toolbox:40

# setup rpmfusion repos
RUN dnf install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
#RUN dnf config-manager --enable fedora-cisco-openh264 -y

# install mesa with codecs
RUN dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld && \
    dnf swap -y mesa-vdpau-drivers mesa-vdpau-drivers-freeworld

COPY ./packages /
RUN dnf install -y $(cat /packages | grep -v '#' | xargs) && \
    rm -f /packages

# pre set distrobox host links
RUN for f in systemctl journalctl xdg-open firefox flatpak op podman ; do \
    ln -s /usr/bin/distrobox-host-exec /usr/local/bin/$f; \
    done

# make podman command remote
RUN echo -e '#!/bin/sh\nexec /usr/bin/podman --remote "$@"' > /usr/local/bin/podman-remote

LABEL io.containers.autoupdate=registry \
    name="Custom Fedora Toolbox" \
    maintainer=detjensrobert \
    org.opencontainers.image.source="https://github.com/detjensrobert/toolbx-images"
