name: Build images

on:
  workflow_dispatch: # manual trigger
  schedule:
    # 4AM every monday, matches upstream weekly builds on sunday
    - cron: "0 4 * * MON"
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  base-images:
    runs-on: ubuntu-latest
    container:
      image: quay.io/podman/stable:latest
      options: --privileged

    strategy:
      matrix:
        tag:
          - arch
          - fedora
          - ubuntu

    steps: &build_steps
      # the arch container is really big now...
      # remove some huge packages to free up space
      # inspired by https://github.com/easimon/maximize-build-space
      # - name: Maximize build space
      #   run:
      #     sudo rm -rf
      #       /usr/share/dotnet
      #       /usr/local/lib/android
      #       /opt/ghc
      #       /opt/hostedtoolcache/CodeQL

      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install newer Buildah
      #   run: ./install-buildah-from-sid.sh

      - name: Build image
        id: build_image
        run:
          podman build
            --pull=always
            -t ghcr.io/detjensrobert/toolbx-images:${{ matrix.tag }}
            ${{ matrix.tag }}

      - name: Push to GHCR
        run:
          podman push
            ghcr.io/detjensrobert/toolbx-images:${{ matrix.tag }}
            --creds "${{ github.actor }}:${{ github.token }}"
            --compression-format zstd
            --compression-level 20

  deriv-images:
    runs-on: ubuntu-24.04
    container:
      image: quay.io/podman/stable:latest
      options: --privileged

    needs: base-images
    strategy:
      matrix:
        tag:
          - zed
          - vr

    # run same steps as above, but with these tags
    steps: *build_steps
