name: Prune old images

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 0 1 * *' # monthly

permissions:
  contents: read
  packages: write

jobs:
  prune:
    runs-on: ubuntu-24.04
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ github.token }}
          image-names: toolbx-images
          cut-off: 2w
